### ISSUE TITLE
CompassView behaves badly around 0/360 dg

### ISSUE THREAD

**Issue by franktom-tieto** [lukinfx/Horizont_Final#3]
The CompassView behaves badly around 0/360 dg. At this direction, some points are move in opposite way that the other points. I'm living in Vraclavek, and the Straziste hill right in front of my house is almost exactly at bearing 0 degrees, so it's quite painful, and it discredits this excellent application.

Please fix it as soon as possible.

**Comment by lukinfx** [comment]
Dear Tomas, the bug has been fixed and new version of our excellent
application can be found on our local server (192.168.100.201/Dev).
Please make sure everything works fine and let us know.

Dne čt 2. 7. 2020 10:00 uživatel Tomas <notifications@github.com> napsal:

**Comment by franktom-tieto** [comment]
I'm happy to confirm, that it works as expected.
Good job. Thank you.
